[profile.default]

solc_version = "0.8.24"
evm_version = "cancun"

libraries = []
libs = ['lib']
optimizer = true
optimizer_runs = 1776
out = 'out'
src = 'src'
test = 'test'
# 
# See more config options https://github.com/foundry-rs/foundry/tree/master/config