[profile.default]

solc_version = "0.8.24"
evm_version = "cancun"

block_base_fee_per_gas = 0
block_coinbase = '0x0000000000000000000000000000000000000000'
block_difficulty = 0
block_number = 0
block_timestamp = 0
cache = true
cache_path = 'cache'
extra_output = []
extra_output_files = []
ffi = false
force = false
fuzz_max_global_rejects = 65536
fuzz_max_local_rejects = 1024
fuzz_runs = 1000
gas_limit = 9223372036854775807
gas_price = 0
gas_reports = ['*']
ignored_error_codes = [1878]
libraries = []
libs = ['lib']
names = false
offline = false
optimizer = true
optimizer_runs = 1776
out = 'out'
sizes = false
src = 'src'
test = 'test'
verbosity = 0
via_ir = false

# See more config options https://github.com/foundry-rs/foundry/tree/master/config